project_id = "krlnrzwshjwupiklzblz"

[functions.send-whatsapp]
verify_jwt = false

[functions.zapi-webhooks]
verify_jwt = false

[functions.mercadopago-payment]
verify_jwt = false

[functions.store-chat]
verify_jwt = false
