project_id = "krlnrzwshjwupiklzblz"

[functions.import-legacy-products]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.zapi-webhooks]
verify_jwt = false

[functions.mercadopago-payment]
verify_jwt = false

[functions.store-chat]
verify_jwt = false

[functions.abandoned-cart-notify]
verify_jwt = false

[functions.abandoned-cart]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.public-quote]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.low-stock-alert]
verify_jwt = false

[functions.ai-tryon]
verify_jwt = false

[functions.affiliate-analytics]
verify_jwt = false

[functions.import-data]
verify_jwt = false

[functions.api-import]
verify_jwt = false

[functions.melhor-envio]
verify_jwt = false
